name: Generate Pacman

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate pacman.svg
        uses: ashtom/github-contribution-graph-pacman@v1.0.0
        with:
          github_user_name: Brunobgr08

      - name: push pacman.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
